---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - template-post
  - template-list-page
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{posts/*,profiles/*}"
  templates:
  - template-page
  - template-landing-page
- type: heading
  label: Configure Site
- type: document
  path: data/config.yaml
  label: Site Options
- type: document
  path: data/styles.yaml
  label: Site Styles
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
